---
# Basic Vault Event Monitoring
#
# This example demonstrates basic monitoring of HashiCorp Vault KV v2 events
# using the vault_events plugin. It captures write, delete, and patch operations.
#
# Prerequisites:
#   - Vault Enterprise 1.13+ or HCP Vault Dedicated (Community Edition not supported)
#   - Vault server running and accessible
#   - Valid Vault token with appropriate permissions
#
# Usage:
#   export VAULT_ADDR="http://127.0.0.1:8200"
#   export VAULT_TOKEN="myroot"
#   ansible-rulebook --env-vars VAULT_ADDR,VAULT_TOKEN -i inventory.yml --rulebook basic-monitoring.yml
#
# Testing:
#   Run this rulebook in background, then generate test events:
#   vault kv put secret/test username=testuser password=secret123
#   vault kv patch secret/test department=engineering
#   vault kv delete secret/test

- name: Basic Vault Event Monitoring
  hosts: localhost
  gather_facts: false

  sources:
    - gitrgoliveira.vault_eda.vault_events:
        vault_addr: "{{ VAULT_ADDR | default('http://127.0.0.1:8200') }}"
        vault_token: "{{ VAULT_TOKEN }}"
        event_paths:
          - "kv-v2/data-*"
        verify_ssl: false
        ping_interval: 20

  rules:
    - name: Log KV Write Events
      condition: event.data.event_type == "kv-v2/data-write"
      action:
        debug:
          msg: "Secret WRITTEN to {{ event.data.event.metadata.data_path }} (version {{ event.data.event.metadata.current_version }})"

    - name: Log KV Delete Events
      condition: event.data.event_type == "kv-v2/data-delete"
      action:
        debug:
          msg: "Secret DELETED from {{ event.data.event.metadata.path | default('unknown') }}"

    - name: Log KV Patch Events
      condition: event.data.event_type == "kv-v2/data-patch"
      action:
        debug:
          msg: "Secret PATCHED at {{ event.data.event.metadata.data_path }} (version {{ event.data.event.metadata.current_version }})"

    - name: Log All Other Events
      condition: event.data.event_type not in ["kv-v2/data-write", "kv-v2/data-delete", "kv-v2/data-patch"]
      action:
        debug:
          msg: "Other event: {{ event.data.event_type }}"
