---
# Vault Event Monitoring with Server-Side Filtering
#
# This example demonstrates server-side filtering of HashiCorp Vault events using
# go-bexpr boolean expressions. Only kv-v2/data-write events are sent from Vault
# to the client, reducing bandwidth and processing overhead.
#
# Prerequisites:
#   - Vault Enterprise 1.13+ or HCP Vault Dedicated (Community Edition not supported)
#   - Vault server running and accessible
#   - Valid Vault token with appropriate permissions
#
# Usage:
#   export VAULT_ADDR="http://127.0.0.1:8200"
#   export VAULT_TOKEN="myroot"
#   ansible-rulebook --env-vars VAULT_ADDR,VAULT_TOKEN -i inventory.yml --rulebook filter-monitoring.yml
#
# Testing:
#   # These operations will be captured (write operations):
#   vault kv put secret/filtered-test username=user password=pass
#   vault kv put secret/another-test data=hello
#
#   # These operations will NOT be captured due to server-side filter:
#   vault kv delete secret/filtered-test  # delete operations filtered out
#   vault kv patch secret/another-test updated=true  # patch operations filtered out

- name: Vault Event Monitoring with Filters
  hosts: localhost
  gather_facts: false

  sources:
    - gitrgoliveira.vault_eda.vault_events:
        vault_addr: "{{ VAULT_ADDR | default('http://127.0.0.1:8200') }}"
        vault_token: "{{ VAULT_TOKEN }}"
        event_paths:
          - "kv-v2/*"
        filter_expression: 'event_type == "kv-v2/data-write"'
        verify_ssl: false
        ping_interval: 20

  rules:
    - name: Write Operations
      condition: true  # Filter already applied server-side
      action:
        debug:
          msg: "WRITE OPERATION: {{ event.data.event_type }} at {{ event.data.event.metadata.data_path }}"
