namespace: gitrgoliveira
name: vault_eda
version: 0.1.0
description: HashiCorp Vault Enterprise Event-Driven Automation plugin for agentless rotation of Vault secrets, using real-time event monitoring via WebSocket
readme: README.md
repository: https://github.com/gitrgoliveira/vault-eda-delivery
homepage: https://github.com/gitrgoliveira/vault-eda-delivery
documentation: https://github.com/gitrgoliveira/vault-eda-delivery/blob/main/README.md
issues: https://github.com/gitrgoliveira/vault-eda-delivery/issues
authors:
  - Ricardo Oliveira
license:
  - MPL-2.0
tags:
  - vault
  - hashicorp
  - event_driven_automation
  - eda
  - websocket
  - monitoring
  - security
  - kv
dependencies: {}